version: '3'
services:
  hzMgmt:
    image: hazelcast/management-center:3.12.6
    environment:
      - JAVA_OPTS=-Dhazelcast.mc.healthCheck.enable=true
    ports:
      - "8080:8080"
      - "8081:8081"
  hzServer:
    depends_on: hzMgmt
    image: asakchris/aws-hazelcast-hazelcast-server:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-Dspring.hazelcast.config=classpath:hazelcast-local.xml
    ports:
      - "8000:8080"
      - "8001:8081"
      - "5701:5701"
  hzClient:
    depends_on: hzServer
    image: asakchris/aws-hazelcast-hazelcast-server:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-Dspring.hazelcast.config=classpath:hazelcast-local.xml
    ports:
      - "8002:8080"
      - "8003:8081"