version: '3'
services:
  hzServer:
    image: asakchris/aws-hazelcast-hazelcast-server:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-Dspring.hazelcast.config=classpath:hazelcast-aws.xml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "5701:5701"
  hzClient:
    image: asakchris/aws-hazelcast-hazelcast-server:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=-Dspring.hazelcast.config=classpath:hazelcast-aws.xml
    ports:
      - "8002:8000"
      - "8003:8001"