server:
  port: 8080
  servlet:
    context-path: /api/v1/hz/server

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: Hazecast-Server